name: 'ActionSpec, LLC'
favicon: null
layout_spectrum: 0.75746
typography_spectrum: 1
title: ActionSpec LLC - Technology Services for Small Business and Startups
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0073c5'
    - '#ffffff'
    - '#4d9dd7'
    - '#82bae2'
    - '#a8cfeb'
  brandStrength: 1
  lightness: 0.8409637294244021
  saturation: 0.8547534267418087
  rhythmicContrast: 0.11022583674639463
purpose: []
